name: SugoiApi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  setup-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@d8af2f43ce846ab2abc7274f8d18fd10dc5a1345
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, json, openssl, session, xmlwriter, simplexml, dom, xml, curl, phar, iconv, fileinfo, zip, gd, intl
      - name: Install dependencies
        run: composer install
      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix -v
      - name: Run PHPUnit
        run: vendor/bin/phpunit
